import { ToolDefinition } from "@/lib/types";

export const toolCatalog: ToolDefinition[] = [
  {
    key: "cursor",
    label: "Cursor",
    vendor: "Anysphere",
    category: "assistant",
    supportsCreditsHint: true,
    plans: [
      {
        key: "hobby",
        label: "Hobby",
        priceMonthly: 0,
        priceType: "account",
        bestFor: ["coding"],
        sourceUrl: "https://cursor.com/pricing",
        sourceNote: "Cursor Hobby is listed as free.",
      },
      {
        key: "pro",
        label: "Pro",
        priceMonthly: 20,
        priceType: "account",
        bestFor: ["coding"],
        sourceUrl: "https://cursor.com/pricing",
        sourceNote: "Cursor Pro is listed at $20/month.",
      },
      {
        key: "business",
        label: "Business (Teams)",
        priceMonthly: 40,
        priceType: "seat",
        bestFor: ["coding", "mixed"],
        sourceUrl: "https://cursor.com/pricing",
        sourceNote: "Cursor Teams is listed at $40/user/month.",
      },
      {
        key: "enterprise",
        label: "Enterprise",
        priceMonthly: null,
        priceType: "custom",
        bestFor: ["coding", "mixed"],
        sourceUrl: "https://cursor.com/pricing",
        sourceNote: "Cursor Enterprise is custom priced.",
      },
    ],
  },
  {
    key: "copilot",
    label: "GitHub Copilot",
    vendor: "GitHub",
    category: "assistant",
    supportsCreditsHint: false,
    plans: [
      {
        key: "individual",
        label: "Individual (Pro)",
        priceMonthly: 10,
        priceType: "account",
        bestFor: ["coding"],
        sourceUrl: "https://github.com/features/copilot/plans",
        sourceNote: "GitHub Copilot Pro is listed at $10/month.",
      },
      {
        key: "business",
        label: "Business",
        priceMonthly: 19,
        priceType: "seat",
        bestFor: ["coding", "mixed"],
        sourceUrl: "https://github.com/features/copilot/plans",
        sourceNote: "GitHub Copilot Business is listed at $19/user/month.",
      },
      {
        key: "enterprise",
        label: "Enterprise",
        priceMonthly: 39,
        priceType: "seat",
        bestFor: ["coding", "mixed"],
        sourceUrl: "https://github.com/features/copilot/plans",
        sourceNote: "GitHub Copilot Enterprise is listed at $39/user/month.",
      },
    ],
  },
  {
    key: "claude",
    label: "Claude",
    vendor: "Anthropic",
    category: "assistant",
    supportsCreditsHint: true,
    plans: [
      {
        key: "free",
        label: "Free",
        priceMonthly: 0,
        priceType: "account",
        bestFor: ["writing", "research", "mixed"],
        sourceUrl: "https://claude.com/pricing",
        sourceNote: "Claude Free is listed at $0.",
      },
      {
        key: "pro",
        label: "Pro",
        priceMonthly: 20,
        priceType: "account",
        bestFor: ["writing", "research", "mixed", "coding"],
        sourceUrl: "https://claude.com/pricing",
        sourceNote: "Claude Pro is $20/month when billed monthly.",
      },
      {
        key: "max",
        label: "Max",
        priceMonthly: 100,
        priceType: "account",
        bestFor: ["research", "mixed", "coding"],
        sourceUrl: "https://claude.com/pricing",
        sourceNote: "Claude Max starts at $100/month.",
      },
      {
        key: "team",
        label: "Team",
        priceMonthly: 30,
        priceType: "seat",
        minimumSeats: 5,
        bestFor: ["mixed", "research", "writing", "coding"],
        sourceUrl: "https://support.anthropic.com/en/articles/9267289-how-is-my-bill-calculated",
        sourceNote: "Claude Team monthly is $30/member with a 5-seat minimum.",
      },
      {
        key: "enterprise",
        label: "Enterprise",
        priceMonthly: null,
        priceType: "custom",
        bestFor: ["mixed", "research", "writing", "coding"],
        sourceUrl: "https://claude.com/pricing",
        sourceNote: "Claude Enterprise is custom priced.",
      },
      {
        key: "api",
        label: "API direct",
        priceMonthly: null,
        priceType: "usage",
        bestFor: ["coding", "data", "mixed"],
        sourceUrl: "https://www.anthropic.com/api",
        sourceNote: "Claude API pricing is usage based.",
      },
    ],
  },
  {
    key: "chatgpt",
    label: "ChatGPT",
    vendor: "OpenAI",
    category: "assistant",
    supportsCreditsHint: true,
    plans: [
      {
        key: "plus",
        label: "Plus",
        priceMonthly: 20,
        priceType: "account",
        bestFor: ["writing", "research", "data", "mixed", "coding"],
        sourceUrl: "https://openai.com/chatgpt/pricing",
        sourceNote: "ChatGPT Plus is listed at $20/month.",
      },
      {
        key: "team",
        label: "Team / Business",
        priceMonthly: 30,
        priceType: "seat",
        minimumSeats: 2,
        bestFor: ["mixed", "writing", "research", "data", "coding"],
        sourceUrl: "https://openai.com/chatgpt/pricing",
        sourceNote:
          "ChatGPT Business is listed at $25/user/month annually or $30/user/month monthly.",
      },
      {
        key: "enterprise",
        label: "Enterprise",
        priceMonthly: null,
        priceType: "custom",
        bestFor: ["mixed", "writing", "research", "data", "coding"],
        sourceUrl: "https://openai.com/chatgpt/pricing",
        sourceNote: "ChatGPT Enterprise is custom priced.",
      },
      {
        key: "api",
        label: "API direct",
        priceMonthly: null,
        priceType: "usage",
        bestFor: ["coding", "data", "mixed"],
        sourceUrl: "https://openai.com/api/pricing",
        sourceNote: "OpenAI API pricing is usage based and billed separately from ChatGPT.",
      },
    ],
  },
  {
    key: "anthropic_api",
    label: "Anthropic API",
    vendor: "Anthropic",
    category: "api",
    supportsCreditsHint: true,
    plans: [
      {
        key: "direct",
        label: "API direct",
        priceMonthly: null,
        priceType: "usage",
        bestFor: ["coding", "data", "mixed"],
        sourceUrl: "https://www.anthropic.com/pricing#api",
        sourceNote: "Anthropic API pricing is usage based.",
      },
    ],
  },
  {
    key: "openai_api",
    label: "OpenAI API",
    vendor: "OpenAI",
    category: "api",
    supportsCreditsHint: true,
    plans: [
      {
        key: "direct",
        label: "API direct",
        priceMonthly: null,
        priceType: "usage",
        bestFor: ["coding", "data", "mixed"],
        sourceUrl: "https://openai.com/api/pricing",
        sourceNote: "OpenAI API pricing is usage based.",
      },
    ],
  },
  {
    key: "gemini",
    label: "Gemini",
    vendor: "Google",
    category: "assistant",
    supportsCreditsHint: false,
    plans: [
      {
        key: "pro",
        label: "Pro",
        priceMonthly: 19.99,
        priceType: "account",
        bestFor: ["research", "writing", "mixed", "coding"],
        sourceUrl: "https://gemini.google/us/subscriptions/?hl=en",
        sourceNote: "Google AI Pro is listed at $19.99/month.",
      },
      {
        key: "ultra",
        label: "Ultra",
        priceMonthly: 99.99,
        priceType: "account",
        bestFor: ["research", "mixed", "coding"],
        sourceUrl: "https://gemini.google/us/subscriptions/?hl=en",
        sourceNote: "Google AI Ultra starts at $99.99/month.",
      },
      {
        key: "api",
        label: "API direct",
        priceMonthly: null,
        priceType: "usage",
        bestFor: ["coding", "data", "mixed"],
        sourceUrl: "https://ai.google.dev/gemini-api/docs/pricing?hl=en",
        sourceNote: "Gemini API pricing is usage based.",
      },
    ],
  },
  {
    key: "v0",
    label: "v0",
    vendor: "Vercel",
    category: "builder",
    supportsCreditsHint: false,
    plans: [
      {
        key: "free",
        label: "Free",
        priceMonthly: 0,
        priceType: "account",
        bestFor: ["coding", "mixed"],
        sourceUrl: "https://v0.dev/docs/pricing",
        sourceNote: "v0 Free is listed at $0/month.",
      },
      {
        key: "team",
        label: "Team",
        priceMonthly: 30,
        priceType: "seat",
        bestFor: ["coding", "mixed"],
        sourceUrl: "https://v0.dev/docs/pricing",
        sourceNote: "v0 Team is listed at $30/user/month.",
      },
      {
        key: "business",
        label: "Business",
        priceMonthly: 100,
        priceType: "seat",
        bestFor: ["coding", "mixed"],
        sourceUrl: "https://v0.dev/docs/pricing",
        sourceNote: "v0 Business is listed at $100/user/month.",
      },
    ],
  },
];

export function getToolDefinition(toolKey: string) {
  return toolCatalog.find((tool) => tool.key === toolKey);
}

export function getPlanDefinition(toolKey: string, planKey: string) {
  return getToolDefinition(toolKey)?.plans.find((plan) => plan.key === planKey);
}
